---
# Source: spring-petclinic-chart/templates/app.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
---
# Source: spring-petclinic-chart/templates/app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      containers:
        - name: prometheus
          image: "hongphuchcmus/spring-petclinic-prometheus:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: prometheus
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tracing-server.tracing.svc.cluster.local:9411/api/v2/spans"
          resources:
            {}
